language: node_js
node_js:
  - 0.10
env:
  - NODE_ENV=ci
services:
  - mongodb
  - neo4j
  - elasticsearch
before_install:
after_success:
notifications:
  email:
    - gabriel.mancini@gmail.com
    - hzucareli@gmail.com
